info:
  contact: {}
paths:
  /ping:
    get:
      description: Возвращает pong
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Проверка доступности сервиса
      tags:
      - health
swagger: "2.0"
